### ISSUE TITLE
I can‘t reproduce ur result

### ISSUE THREAD

**Issue by agenthong** [kwea123/MVSNet_pl#4]
I’ve tried 1 batchsize, 192depthnum and 2 batchsize, 128 depthnum in training but the results did't match yours. @kwea123 
1 batchsize, 192depthnum
![image](https://user-images.githubusercontent.com/59220627/78666921-a8644980-790a-11ea-81b0-ed4b71fa2d04.png)

2 batchsize, 128 depthnum
![image](https://user-images.githubusercontent.com/59220627/78666943-b1551b00-790a-11ea-8b77-92a5f2963d1f.png)

Here are the issues: 
1) My results are far from yours； 
2）It seems that 1 batchsize, 192depthnum perfomance better than 2 batchsize, 128 depthnum.

**Comment by kwea123** [comment]
What is your command for training?
Is it the same as ?
```
python train.py \
  --root_dir $DTU_DIR \
  --num_epochs 6 --batch_size 1 \
  --n_depths 192 --interval_scale 1.06 \
  --optimizer adam --lr 1e-3 --lr_scheduler cosine
```

**Comment by agenthong** [comment]
a little bit diff, my command is the following: 
```
python train.py \
  --root_dir $DTU_DIR \
  --num_epochs 16 --batch_size 1 \
  --n_depths 192 --interval_scale 0.8 \
  --optimizer adam --lr 1e-3 --lr_scheduler cosine
```
But I think it should produce the same result

**Comment by kwea123** [comment]
No it won't. the `--interval_scale` is as important as `--n_depths`
It means how much factor to multiply to the original "2.5mm depth interval".
The depth range is from 425 to 935, so you need to adjust `--n_depths` and `--interval_scale` so that they make up 510mm range.
For example, `--n_depths 256` means the interval should be 510/(256-1)=2, so `--interval_scale` must be 2/2.5=`0.8`.
Another example, `--n_depths 192` means the interval should be 510/(192-1)~=2.65, `--interval_scale` must be 2.65/2.5=`1.06`.
Same calculation will lead to `--interval_scale 1.6` for `--n_depths 128`.
It is somehow complicated for the first time you see this, but doing some calculation will make it more clear, as I did when I just started.

Maybe I should add this explanation in the readme. Edit: this explanation is added.

**Comment by agenthong** [comment]
@kwea123
Your explanation make sense indeed,  I understand it clearly. Thanks a lot.

**Comment by seekever** [comment]
> ame calculation will lead to `-`

As you mentioned, --n_depths 192 means the interval should be 510/(192-1)~=2.67 (rather than 2.65), thus --interval_scale should be 2.67/2.5=1.068  (rather than 1.06).
Is it more accurate?
