### ISSUE TITLE
About inverse depth

### ISSUE THREAD

**Issue by CC9310** [kwea123/MVSNet_pl#5]
I saw some papers (like RMVSNet) say "when reconstructing larger scene, inverse depth is a good choice", but i can't understand the equation of "inverse depth", can you explain this? thanks a lot.

**Comment by kwea123** [comment]
Which equation? Can you write it here?

**Comment by xinchengTang** [comment]
Given the depth range [dmin; dmax], we sample depth values using the inverse depth setting:
$$
d_{i} = ((\frac{1}{d_{min}} -\frac{1}{d_{max}})\frac{i}{D-1} + \frac{1}{d_{max}})^{-1}
$$
where i is the index of the depth sampling and D is the depth sample number. To determine the sample number D, we assume that the spatial image resolution should be the same as the temporal depth resolution...

> I copy this in RMVSNet supplment material, but I don't understand what the formula means.

**Comment by CC9310** [comment]
![2020-09-15_142359](https://user-images.githubusercontent.com/40813751/93173462-20a72480-f75f-11ea-9df6-74066748e57e.png)
whether this formula aims at sampling the depth nonuniformly? Is there some other meanings?

**Comment by kwea123** [comment]
The idea is to sample more smaller depths, for example if the range is 400-900, then it will sample like 400, 410, 420, ... and very sparse around 900. This allows the model to focus more on the foreground object instead of the background.
Yes it aims at sampling the depth non-uniformly. In practice inverse depth sampling is common.

**Comment by CC9310** [comment]
@kwea123 thanks for your reply 👍
